/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.friascorp.plaza.store.views.panels;

import org.friascorp.plaza.store.views.panels.controlpanels.Control_pingresosegresos;

/**
 *
 * @author ntnfr
 */
public class Panel_ingresosEgresos extends javax.swing.JPanel {

    /**
     * Creates new form Panel_ingresos
     */
    public Panel_ingresosEgresos() {
        initComponents();
        new Control_pingresosegresos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cabecera_ingreEgre = new javax.swing.JPanel();
        pie_btningresos = new javax.swing.JButton();
        pie_btnegresos = new javax.swing.JButton();
        pnl_ingreegrecontenedor = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 153));

        pnl_cabecera_ingreEgre.setBackground(new java.awt.Color(255, 102, 0));

        pie_btningresos.setText("INGRESOS");
        pie_btningresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pie_btningresosActionPerformed(evt);
            }
        });

        pie_btnegresos.setText("EGRESOS");

        javax.swing.GroupLayout pnl_cabecera_ingreEgreLayout = new javax.swing.GroupLayout(pnl_cabecera_ingreEgre);
        pnl_cabecera_ingreEgre.setLayout(pnl_cabecera_ingreEgreLayout);
        pnl_cabecera_ingreEgreLayout.setHorizontalGroup(
            pnl_cabecera_ingreEgreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cabecera_ingreEgreLayout.createSequentialGroup()
                .addComponent(pie_btningresos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pie_btnegresos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_cabecera_ingreEgreLayout.setVerticalGroup(
            pnl_cabecera_ingreEgreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pie_btnegresos, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
            .addComponent(pie_btningresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_ingreegrecontenedor.setBackground(new java.awt.Color(0, 0, 204));
        pnl_ingreegrecontenedor.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_ingreegrecontenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_cabecera_ingreEgre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnl_cabecera_ingreEgre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_ingreegrecontenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pie_btningresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pie_btningresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pie_btningresosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton pie_btnegresos;
    public javax.swing.JButton pie_btningresos;
    private javax.swing.JPanel pnl_cabecera_ingreEgre;
    public javax.swing.JPanel pnl_ingreegrecontenedor;
    // End of variables declaration//GEN-END:variables
}
